{% set version = "2022.07.0" %}

package:
  name: geocat-viz
  version: {{ version }}

source:
  url: https://github.com/NCAR/geocat-viz/archive/v{{ version }}.tar.gz   # For building from a specific tag's tarball
  sha256: a8840ffa8785e09084a1cbc3e7abc3e11de250e1c56c80eec363e3bbe09a2021

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cartopy
    - cmaps
    - matplotlib
    - metpy
    - numpy
    - scikit-learn
    - xarray

test:
  requires:
    - pytest
  imports:
    - geocat
    - geocat.viz

about:
  home: https://geocat.ucar.edu/
  summary: GeoCAT-viz is a collection of utility functions to make Python plotting with Matplotlib and Cartopy more like NCL (NCAR Command Language).
  dev_url: https://github.com/NCAR/geocat-viz
  doc_url: https://geocat-viz.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - NCAR/geocat # GeoCAT https://github.com/orgs/NCAR/teams/geocat
    - anissa111 # A. Zacharias https://github.com/anissa111
    - erogluorhan # O. Eroglu https://github.com/erogluorhan
    - hCraker # H. Craker https://github.com/hCraker
    - michaelavs # M. Sizemore https://github.com/michaelavs
    - pilotchute # A. Kootz https://github.com/pilotchute
